project:
  type: website
  output-dir: "_site"
  pre-render:
    - code/create_posts.R

website:
  title: "Susan Vanderplas"
  site-url: "srvanderplas.github.io"
  navbar:
    right:
      - about.qmd
      - text: "More"
        menu:
          - publications.qmd
          - courses.qmd
          - talks.qmd
          - other.qmd
      - icon: github
        href: https://github.com/srvanderplas
      - icon: file-person
        href: https://srvanderplas.github.io/CV/CV.pdf
      - icon: fa-bluesky
        href: srvanderplas.bsky.social
      - icon: mastodon
        href: https://mastodon.social/@srvanderplas
format:
  html:
    theme: pulse
    css: styles.css


freeze: auto
